### ISSUE TITLE
Documentation outdated or just me?

### ISSUE THREAD

**Issue by flindblom-ohmy** [loevgaard/SyliusBrandPlugin#57]
Hello!

I'm seeing some discrepancies between the documentation and my code implementation. My composer file has:

"require": {
        "php": "^7.2",
        "loevgaard/sylius-brand-plugin": "^1.3",
        "sylius/sylius": "~1.5.0"

The documentation says:

use Loevgaard\SyliusBrandPlugin\Model\ProductInterface as LoevgaardSyliusBrandPluginProductInterface;
use Loevgaard\SyliusBrandPlugin\Model\ProductTrait as LoevgaardSyliusBrandPluginProductTrait;

But that doesn't work. This does work, however:

use Loevgaard\SyliusBrandPlugin\Entity\BrandAwareInterface;
use Loevgaard\SyliusBrandPlugin\Entity\ProductTrait;

There is a similar problem with the ProductRepository, where the suggested **use** statements don't fit the actual code.

Is this due to to me using bad versions of Sylius and/or the plugin, or is the documentation out of date?

Thanks.

**Comment by loevgaard** [comment]
Hi @flindblom-ohmy 

Thank you for your issue :)

The plugin is right now in v2 beta, which you can use if you want to use the newest code. We will probably release a stable v2 in the coming 3-4 weeks, so my recommendation is you use the v2 beta since it is already very stable.

The documentation for the 1.x plugin can be found here: https://github.com/loevgaard/SyliusBrandPlugin/tree/v1.3.2

**Comment by flindblom-ohmy** [comment]
Thank you @loevgaard! 

I just found the UPGRADE-2.0.md, so I'm hoping that will take care of everything.

**Comment by loevgaard** [comment]
Oh, yeah, forgot to link to that. Hope you'll figure it out. If not, do not hesitate to reopen the issue :)
